# AndroidX desteği
android.useAndroidX=true
android.enableJetifier=true

# Gradle bellek ve derleme ayarları
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.defaults.buildfeatures.buildconfig=true

# Codemagic AGP 8+/9+ yeni DSL çakışmasını engelleme
android.experimental.artificiallyEnableOldModel=true
